// Code generated by devcloud codegen. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
package athena

import "github.com/skyoo2003/devcloud/internal/plugin"

func init() {
	plugin.DefaultRegistry.Register("athena", func(cfg plugin.PluginConfig) plugin.ServicePlugin {
		return &Provider{}
	})
}
