documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "*.md"
          - "README.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/dependabot.yml"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "build/package/**/*"
          - "deployments/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**/*"
          - "**/*_test.go"

codegen:
  - changed-files:
      - any-glob-to-any-file:
          - "internal/codegen/**/*"
          - "api/smithy/**/*"
          - "tools/codegen/**/*"

services:
  - changed-files:
      - any-glob-to-any-file:
          - "internal/services/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"
