FROM --platform=$BUILDPLATFORM alpine:3.21

RUN adduser --system --home /devcloud appuser
VOLUME /devcloud
WORKDIR /devcloud
ARG TARGETOS
ARG TARGETARCH
COPY ${TARGETOS}/${TARGETARCH}/devcloud /usr/bin/devcloud

USER appuser
ENTRYPOINT ["devcloud"]
