// SPDX-License-Identifier: Apache-2.0

// internal/codegen/gen_types.go
package codegen

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// Generator holds the template directory and renders code from Smithy models.
type Generator struct {
	templateDir string
}

// NewGenerator creates a new Generator that loads templates from templateDir.
func NewGenerator(templateDir string) *Generator {
	return &Generator{templateDir: templateDir}
}

// renderTemplate loads the named template file from the generator's template
// directory, executes it with data, and returns the rendered string.
func (g *Generator) renderTemplate(name string, data any) (string, error) {
	tmplPath := filepath.Join(g.templateDir, name)
	tmpl, err := template.ParseFiles(tmplPath)
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", tmplPath, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}

// structureData is the template data for a structure shape.
type structureData struct {
	Name    string
	Members []memberData
}

type memberData struct {
	Name    string
	GoType  string
	JSONTag string
	XMLTag  string
}

// listData is the template data for a list shape.
type listData struct {
	Name     string
	ElemType string
}

// mapData is the template data for a map shape.
type mapData struct {
	Name      string
	KeyType   string
	ValueType string
}

// aliasData is the template data for a simple type alias (enum, string, integer, etc.).
type aliasData struct {
	Name   string
	GoType string
}

// typesTemplateData is the top-level data passed to types.go.tmpl.
type typesTemplateData struct {
	PkgName    string
	Structures []structureData
	Lists      []listData
	Maps       []mapData
	Aliases    []aliasData
}

// resolveGoType converts a GoType string from the model into the appropriate
// Go type for use in a generated struct field. Structure references become
// pointer types; primitives and others pass through unchanged.
func resolveGoType(goType string, shapes map[string]*Shape) string {
	if shape, ok := shapes[goType]; ok && shape.Type == ShapeStructure {
		return "*" + goType
	}
	return goType
}

// toJSONTag converts a member name to a json struct tag (lowercase first char).
func toJSONTag(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// exportName ensures a name starts with an uppercase letter so it is exported in Go.
func exportName(name string) string {
	if name == "" {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

// GenerateTypes produces a Go source file containing struct definitions,
// list type aliases, and map type aliases for all shapes in model.
func (g *Generator) GenerateTypes(pkgName string, model *SmithyModel) (string, error) {
	data := typesTemplateData{PkgName: pkgName}

	// Collect shape names in sorted order for deterministic output.
	names := make([]string, 0, len(model.Shapes))
	for name := range model.Shapes {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		shape := model.Shapes[name]
		switch shape.Type {
		case ShapeStructure:
			// Skip error shapes — they are generated by gen_errors.go
			if shape.ErrorTrait != nil {
				continue
			}
			sd := structureData{Name: name}
			for _, m := range shape.Members {
				goType := resolveGoType(m.GoType, model.Shapes)
				sd.Members = append(sd.Members, memberData{
					Name:    exportName(m.Name),
					GoType:  goType,
					JSONTag: toJSONTag(m.Name),
					XMLTag:  m.Name,
				})
			}
			data.Structures = append(data.Structures, sd)

		case ShapeList:
			if shape.ListMember == nil {
				continue
			}
			elemType := resolveGoType(shape.ListMember.GoType, model.Shapes)
			data.Lists = append(data.Lists, listData{Name: name, ElemType: elemType})

		case ShapeMap:
			if shape.KeyMember == nil || shape.ValueMember == nil {
				continue
			}
			keyType := resolveGoType(shape.KeyMember.GoType, model.Shapes)
			valType := resolveGoType(shape.ValueMember.GoType, model.Shapes)
			data.Maps = append(data.Maps, mapData{Name: name, KeyType: keyType, ValueType: valType})

		case ShapeDocument, ShapeUnion:
			data.Aliases = append(data.Aliases, aliasData{Name: name, GoType: "interface{}"})

		case ShapeIntEnum:
			data.Aliases = append(data.Aliases, aliasData{Name: name, GoType: "int32"})
		}
	}

	rendered, err := g.renderTemplate("types.go.tmpl", data)
	if err != nil {
		return "", err
	}

	// Remove unused "time" import if time.Time is not referenced.
	if !strings.Contains(rendered, "time.Time") {
		rendered = strings.Replace(rendered, "\nimport (\n\t\"time\"\n)\n", "\n", 1)
	}

	return rendered, nil
}
