// SPDX-License-Identifier: Apache-2.0

package codegen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateAll(t *testing.T) {
	model := loadTestModel(t)
	gen := NewGenerator("templates")
	outDir := t.TempDir()

	err := gen.GenerateAll(model, outDir, "")
	require.NoError(t, err)

	serviceDir := filepath.Join(outDir, "s3")
	files := []string{
		"types.go", "interface.go", "base_provider.go",
		"serializer.go", "deserializer.go", "router.go", "errors.go",
	}
	for _, f := range files {
		path := filepath.Join(serviceDir, f)
		assert.FileExists(t, path, "missing generated file: %s", f)

		content, err := os.ReadFile(path)
		require.NoError(t, err)
		assert.Contains(t, string(content), "Code generated by devcloud codegen")
	}
}
