services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4747:4747"
    volumes:
      - ../data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEVCLOUD_SERVICES=s3,sqs,dynamodb,iam,sts,lambda
