#!/usr/bin/env bash
# scripts/generate-imports.sh
# Generates cmd/devcloud/imports.go with blank imports for all services.
#
# A service package is only registered if this file imports it: registration
# happens in an init(), which never runs for a package nothing imports. So a
# short or empty imports.go does not degrade the binary, it empties it — and
# only in the built artefact, where nothing else notices.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICES_DIR="./internal/services"
OUTPUT="./cmd/devcloud/imports.go"

# Build into a temp file first: the floor check below has to be able to refuse
# without having already truncated a good imports.go. Same reasoning as
# download-smithy-models.sh — a failed run must leave the committed file alone.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" << 'HEADER'
// Code generated by scripts/generate-imports.sh. DO NOT EDIT.
package main

import (
HEADER

count=0
for dir in "$SERVICES_DIR"/*/; do
  pkg=$(basename "$dir")

  # Gate on the package actually calling Register, not on a filename.
  # Registration lives in an init() inside provider.go; no service has ever had
  # a register.go, so gating on that filename skipped all of them and emitted an
  # empty import block. _test.go is excluded so a test that merely mentions
  # Register cannot qualify a package that does not register.
  registers=0
  for f in "$dir"*.go; do
    [ -f "$f" ] || continue
    case "$f" in *_test.go) continue ;; esac
    if grep -q 'DefaultRegistry\.Register(' "$f"; then
      registers=1
      break
    fi
  done
  [ "$registers" -eq 1 ] || continue

  echo "	_ \"github.com/skyoo2003/devcloud/internal/services/${pkg}\"" >> "$tmp"
  count=$((count + 1))
done

echo ")" >> "$tmp"

# Every service package is committed, so a run that finds almost none has a
# broken gate rather than a shrunken fleet. Exiting non-zero is the point: the
# weekly sync workflow regenerates this file, and a silent green run that wrote
# an empty import block is exactly the failure this check exists to stop.
MIN_SERVICES="${MIN_SERVICES:-50}"
if [ "$count" -lt "$MIN_SERVICES" ]; then
  echo "ERROR: found ${count} registering service package(s) under ${SERVICES_DIR}, expected at least ${MIN_SERVICES}." >&2
  echo "Refusing to write a gutted ${OUTPUT}; it is unchanged." >&2
  exit 1
fi

mv "$tmp" "$OUTPUT"
trap - EXIT

gofmt -w "$OUTPUT"
# Reuse the repo's SPDX rule rather than restating it here: that script already
# knows to keep the "Code generated" marker on line 1 and insert SPDX on line 2.
bash "${SCRIPT_DIR}/add-spdx-header.sh" "$OUTPUT"

echo "Generated $OUTPUT with ${count} services"
