#!/usr/bin/env bash
# scripts/generate-imports.sh
# Generates cmd/devcloud/imports.go with blank imports for all services.
set -euo pipefail

SERVICES_DIR="./internal/services"
OUTPUT="./cmd/devcloud/imports.go"

cat > "$OUTPUT" << 'HEADER'
// Code generated by scripts/generate-imports.sh. DO NOT EDIT.
package main

import (
HEADER

for dir in "$SERVICES_DIR"/*/; do
  pkg=$(basename "$dir")
  # Skip directories without register.go
  if [ ! -f "${dir}register.go" ]; then
    continue
  fi
  echo "	_ \"github.com/skyoo2003/devcloud/internal/services/${pkg}\"" >> "$OUTPUT"
done

echo ")" >> "$OUTPUT"

gofmt -w "$OUTPUT"
echo "Generated $OUTPUT"
