// Code generated by devcloud codegen. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
package sts

// NOTE: STS registration is handled by the iam package's STSProvider
// (internal/services/iam/sts_provider.go) which shares the IAM store.
// The generated Provider in this package is not used.
